if (Sys.info()[1] == "Linux") {
  rm(list = ls())
  gc()
  options(future.globals.maxSize = 1e100)
  library(magrittr)
  library(terra)
  # remotes::install_github("rspatial/terra", configure.args = "--with-proj-lib=/opt/homebrew/Cellar/proj/9.0.1/lib/")
  library(raster, exclude = "select")
  library(tidyverse)
  library(tidymodels)
  library(data.table)
  library(lubridate)
  library(ggpmisc)
  library(collapse)
  library(scales)
  library(sf)
  sf_use_s2(F)
  library(readxl)
  library(exactextractr)
  library(fixest)
  library(Matrix)
  library(matrixStats, exclude = "count")
  library(ncdf4)
  library(splines)
  library(mgcv)
  library(furrr)
  library(qs)
  library(ggdist)
} else {
  rm(list = ls())
  gc()
  options(future.globals.maxSize = 1e100)
  library(magrittr)
  library(terra)
  # remotes::install_github("rspatial/terra", configure.args = "--with-proj-lib=/opt/homebrew/Cellar/proj/9.0.1/lib/")
  library(raster, exclude = "select")
  library(tidyverse)
  library(tidymodels)
  library(data.table)
  library(lubridate)
  library(ggpmisc)
  library(collapse)
  if (Sys.info()[1] == "Windows") {
    sysfonts::font_add("Roboto Condensed", "D:/Software/R/R-4.2.3/library/hrbrthemes/fonts/roboto-condensed/RobotoCondensed-Regular.ttf")
  } else {
    sysfonts::font_add("Roboto Condensed", "/Library/Frameworks/R.framework/Resources/library/hrbrthemes/fonts/roboto-condensed/RobotoCondensed-Regular.ttf")
  }
  showtext::showtext_auto()
  showtext::showtext_opts(dpi = 300)
  library(hrbrthemes)
  library(cowplot)
  library(ggh4x)
  library(scales)
  library(patchwork)
  library(sf)
  sf_use_s2(F)
  library(readxl)
  library(exactextractr)
  library(fixest)
  library(Matrix)
  library(matrixStats, exclude = "count")
  library(ncdf4)
  library(splines)
  library(ggside)
  library(ggdensity)
  library(ggupset)
  library(latex2exp)
  library(ggrepel)
  library(mgcv)
  library(ggpointdensity)
  library(viridis)
  library(furrr)
  library(correlation)
  library(qs)
  library(gghighlight)
  library(biscale)
  library(ggdist)
  library(ggtext)
  library(slider)
  library(tidyformula)
  library(kableExtra)
}
